version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    restart: always
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=backend/src/app.py
      - FLASK_DEBUG=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 